apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/os-observability/konflux-opentelemetry?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" &&
      (".tekton/single-arch-build-pipeline.yaml".pathChanged() ||
      ".tekton/otel-bundle-quay-pull-request.yaml".pathChanged() ||
      ".tekton/otel-bundle-quay-push.yaml".pathChanged() ||
      "Dockerfile.bundle".pathChanged() ||
      "bundle-patch/***".pathChanged() ||
      "opentelemetry-operator".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: otel
    appstudio.openshift.io/component: otel-bundle-quay
    pipelines.appstudio.openshift.io/type: build
  name: otel-bundle-quay-on-pull-request
  namespace: rhosdt-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: prefetch-input
    value: '[{"type": "rpm", "path": "./bundle-patch"}]'
  - name: hermetic
    value: "true"
  - name: prefetch-dev-package-managers-enabled
    value: "true"
  - name: output-image
    value: quay.io/redhat-user-workloads/rhosdt-tenant/otel/opentelemetry-bundle-quay:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: Dockerfile.bundle
  - name: path-context
    value: .
  - name: build-source-image
    value: "true"
  pipelineRef:
    name: single-arch-build-pipeline
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
